# Generated by Django 4.0 on 2023-11-02 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0002_balancehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='old_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.DeleteModel(
            name='BalanceHistory',
        ),
    ]
