# Generated by Django 4.0 on 2023-11-03 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0003_balance_old_amount_delete_balancehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='initial_savings',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
