# Generated by Django 4.0 on 2023-11-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0004_balance_initial_savings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='initial_savings',
        ),
        migrations.AddField(
            model_name='balance',
            name='savings',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
