# Generated by Django 4.0 on 2023-11-07 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('myweb', '0005_remove_balance_initial_savings_balance_savings'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_added', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('savings_added', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('amount_history', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('savings_history', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
