# Generated by Django 4.0 on 2023-11-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0006_history'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='balance',
            name='old_amount',
        ),
    ]
