# Generated by Django 4.0 on 2023-11-07 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0007_remove_balance_old_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='savings_added',
        ),
        migrations.RemoveField(
            model_name='history',
            name='savings_history',
        ),
    ]
