# Generated by Django 4.0 on 2023-11-08 13:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0009_rename_history_historybalance_historysavings'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
