# Generated by Django 4.0 on 2023-11-08 13:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0011_remove_historybalance_timestamp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date',
        ),
        migrations.AddField(
            model_name='item',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
