# Generated by Django 4.0 on 2023-11-08 13:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0012_remove_item_date_item_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='datetime',
        ),
        migrations.AddField(
            model_name='item',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
