# Generated by Django 4.0 on 2023-11-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0014_alter_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=30),
        ),
    ]
