# Generated by Django 4.0 on 2023-11-14 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0015_alter_item_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics'),
        ),
    ]
