# Generated by Django 4.0 on 2023-11-24 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0017_feedback_alter_balance_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
