# Generated by Django 4.0 on 2023-11-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0019_item_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price2',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
