# Generated by Django 4.0 on 2023-11-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0020_item_price2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='price2',
            field=models.IntegerField(),
        ),
    ]
