# Generated by Django 4.0 on 2023-12-01 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0021_alter_item_price_alter_item_price2'),
    ]

    operations = [
        migrations.AddField(
            model_name='historybalance',
            name='type',
            field=models.CharField(default='Item', max_length=80),
            preserve_default=False,
        ),
    ]
