# Generated by Django 4.0 on 2023-12-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myweb', '0022_historybalance_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistorySavings',
        ),
    ]
